version: '2'
services:
  mongo:
    image: mongo
  nginx:
    image: nginx
    volumes:
      - ./dist:/var/www/
      - ./default:/etc/nginx/conf.d/default.conf
    environment:
     - NGINX_PORT=80
    links:
      - "web:web"
    ports:
      - "80:80"
    stdin_open: true
    tty: true
  web:
    build: .
    command:  npm start
    volumes:
      - ./OmdbBack/omdbreduxbackend/bin:/app/bin
      - ./OmdbBack/omdbreduxbackend/routes:/app/routes
      - ./OmdbBack/omdbreduxbackend/views:/app/views
      - ./OmdbBack/omdbreduxbackend/public:/app/public
      - ./OmdbBack/omdbreduxbackend/models:/app/models
    links:
      - "mongo:mongo"
    ports:
      - "8080:8080"